version:              '2'

services:
    applications:
      image:          alpine:3.4
      volumes:
        - ../Code:/var/www

    mirlocator:
        build:
            context:  ./mirlocator
        working_dir:  /var/www/mirlocator
        environment:
            - FLASK_APP=main.py
            - FLASK_DEBUG=1
        command: flask run --host=0.0.0.0
        volumes_from:
            - applications
        ports:
            - '5000:5000'
        privileged:   true
